name: health_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  fl_chart: ^0.64.0
  google_generative_ai: ^0.2.3
  intl: ^0.18.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  flutter_tts: ^3.8.5
  flutter_markdown: ^0.6.18
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.1
  flutter_calendar_carousel: ^2.4.1
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.0.0
  flutter_offline: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets configuration would go here
  # assets:
  #   - images/ 